In [1]:
import op_art as xp

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

/Users/tom/projects-workspace/array-tracker/array_tracker/_array_object.py:7: UserWarning: The numpy.array_api submodule is still experimental. See NEP 47.
  import numpy.array_api as nxp


In [2]:
a = xp.arange(6)
a

Array(id=0,
arr=[0 1 2 3 4 5],
src_arr_ids=None,
src_offsets=None)

In [3]:
b = xp.reshape(a, (3, 2))
b

Array(id=1,
arr=[[0 1]
 [2 3]
 [4 5]],
src_arr_ids=[[[0]
  [0]]

 [[0]
  [0]]

 [[0]
  [0]]],
src_offsets=[[[0]
  [1]]

 [[2]
  [3]]

 [[4]
  [5]]])

In [4]:
a = xp.arange(6)
b = xp.reshape(a, (3, 2))
xp.visualize(a, b)

<IPython.core.display.Javascript object>